jazzband/django-push-notifications

- push_notifications/models.py
- tests/mock_responses.py
- tests/test_models.py
> Passing kwargs when sending messages to gcm devices using queryset

- push_notifications/fields.py
`./manage.py migrate` was failing with
`db_type() got multiple values for keyword argument 'connection'`
due to a way `call_with_connection` is implemented in `django/db/models/fields/subclassing.py` in Django 1.3
> Fix Django 1.3 compatibility issue

- push_notifications/apns.py
- tests/__init__.py
- tests/test_management_commands.py
Under python 3 `rune_devices management command` is failing with the folowing error
```
'bytes' object has no attribute 'encode'
push_notifications/apns.py, apns_fetch_inactive_ids:234
```
Let's address this issue by using `codecs` module.
> Add support of python3 for prune_devices management command

- push_notifications/admin.py
- push_notifications/fields.py
The value appears as hex in both /admin/push_notifications/gcmdevice/
and /admin/push_notifications/gcmdevice/pk/
Search will work on both integer and hex values. Assume device_ids
0x01, 0x10 and 0x100; a search on 1 would return 0x01(1) and 0x10(16)
but not 0x100(256). A search on 0x1 would return all three devices
but a search on 0x10 would return 0x10 and 0x100
> Display gcm device_id as hex value in Django admin

- push_notifications/fields.py
When either postgres or mysql is selected as the database engine
attempts to create or update a gcm device using a form and http post
will fail.  The validators were being run against a string value
thus min and max validation were failing.
> Fixed bug that caused an error when creating or updating a gcm device

- push_notifications/api/rest_framework.py
Call the perform_create of the super so it also will save the serializer when the user is not authenticated.
> Fix DeviceViewSetMixin when user is not authenticated

- push_notifications/admin.py
device_id value to hex when sqlite or mysql is configured as the
backend db.
> Fixes issue #192, added a null check before attempting to convert

- push_notifications/models.py
- tests/test_models.py
Since we intend to send notifications only to the active devices. Active filter should be in the query set.
I have added this check in both APNS and GCM querysets. Please review it.
Thanks,
Avichalp
> Adds active filter in APNS and GCM query sets.

- push_notifications/api/rest_framework.py
- tests/test_rest_framework.py
Added UniqueValidator to the GCMDevice Serializer to work around some mysql database limitations. A bandaid for issues mentioned in #184 #197 #216. With tests.
> UniqueValidator on GCMDevice Serializer

- push_notifications/models.py
Iterating through devices is not efficient way to recieve it's
registration ids. It costs additional time on transfeting data,
etc.
> Retrive registration_ids in single query

- tox.ini
The tests in test_rest_framework were not running because they require djangorestframework.
> Added djangorestframework to tox deps list.

- push_notifications/admin.py
- push_notifications/api/rest_framework.py
- push_notifications/fields.py
- tests/test_rest_framework.py
Half of the valid GCM device_id range currently elicits a `ValidationError` due to incorrect validation added in e8d07766e2e89b6ff176e386e88039a3c8cc1554, whereby the submitted value is checked against the signed 64 bit integer maximum rather than the unsigned.
> Correcting rest framework validation of GCMDevice.device_id max value.

- .travis.yml
- README.rst
- setup.py
- tox.ini
Added Django 1.9 to tox test environment
Fixed tox.ini to properly test against all supported
versions of Python, Django and Django Rest Framework
> Dropped support for Python 3.3

- push_notifications/fields.py
On Django 1.9 if the gcm device id is null, an error is thrown
on the to_python method of the HexIntegerField class.
> Fixes an index error that is thrown in the django admin.

- push_notifications/fields.py
Subfieldbase is deprecated and scheduled to be removed with Django
1.10
> Removed call to with_metaclass as it is no longer needed

- push_notifications/api/rest_framework.py
When the serializer is nested the unique validator on registration_id
does not behave correctly.  This is a known issue with DRF
see: https://github.com/tomchristie/django-rest-framework/issues/2403
Added missing allow_null to device_id field
Fixes #270
> Fix bug when using gcm serializer as a nested serializer.

- push_notifications/api/rest_framework.py
Addresses issue #268 
Overrides `perform_update` (similar to `perform_create`) to update Device.user when updating existing devices.
> Update Device.user when updating existing devices via DRF.

- push_notifications/gcm.py
- tests/test_models.py
send a gcm message if the registration id is None
> gcm_send_message and gcm_send_bulk_message will no longer attempt to

- README.rst
The old link was dead; Apple isn't great at keeping old links live.
> Updates ReadMe with new link to APNS intro page.

- README.rst
- push_notifications/gcm.py
gcm_send_bulk_message did not allow passing a registration_ids value of None.
Update README.rst with correct example for send messages to topics
> Fix support for sending GCM messages to topic subscribers.

- README.rst
- push_notifications/apns.py
- tests/test_apns_push_payload.py
Add the thread-id keyword from the [Apple Payload Guide](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW1). 
Includes tests and documentation in the README.
> Allow send_message to set thread-id for APNS

- setup.py
`distutils.core.setup` does not support `python setup.py develop`. Replace with the standard `setuptools.setup` variant makes developing and integrating multiple python modules easier. I also thought distutils was deprecated in favor of setuptools.
> Replace distutils with setuptools

- README.rst
Fix syntax/parameter name errors in code examples in README.rst.
Thanks for your work on django-push-notifications :)
> Fix code examples in README

- push_notifications/api/rest_framework.py
The the request is a PATCH, attrs may not contain id or reg_id.
So use the values from self.instance instead.
> Fix bug in UniqueRegistrationSerializerMixin.

- push_notifications/gcm.py
The refactored send_message method required a registration_id thus
breaking the ability to send messages to topics.
Fixes #369
> Fix fcm/gcm send_message method.

- push_notifications/api/rest_framework.py
- push_notifications/apns.py
- push_notifications/conf/__init__.py
- push_notifications/conf/app.py
- push_notifications/conf/appmodel.py
- push_notifications/conf/base.py
- push_notifications/conf/legacy.py
- push_notifications/gcm.py
- push_notifications/migrations/0005_applicationid.py
- push_notifications/models.py
- push_notifications/settings.py
- push_notifications/utils.py
- push_notifications/wns.py
- setup.cfg
- tests/test_apns_models.py
- tests/test_app_config.py
- tests/test_gcm_push_payload.py
- tests/test_models.py
- tests/test_rest_framework.py
- tests/test_wns.py
Provides backwards compatibility through conf adapters that determine which settings are supported and where the data can be loaded from. This implementation adds three:
* LegacyConfig - supports the existing settings format
* AppConfig - supports a dictionary of application_ids and their settings
* AppModelConfig - supports storing the settings in the database for multiple apps
@jleclanche Consider this a really rough draft. I haven't had much time to test it though the tests pass.  I hope this gives you an idea of what I intend and should replace the other mutli application PR. This one has stubs for the multi-app config and multi-app in a model config. I'd like to get this approved and into the merged with the legacy config adapter just to reduce the number of rebases.
> Enable multiple application support

- README.rst
Passing `topic=...` to PyAPNS2 is mandatory (see https://github.com/Pr0Ger/PyAPNs2/issues/29), the topic isn't auto-guessed from the certificate.
An emtpy APNS_TOPIC setting leads to TopicDisallowed / MissingTopic errors.
> Fix 'APNS_TOPIC' docs

- push_notifications/api/rest_framework.py
DRF GCMDeviceSerializer masks `application_id` field, making it **not available on DRF** views/urls.
To fix it we should either add `application_id` to `fields` or remove the `fields` from Meta class entirely.
APNSDeviceSerializer is not affected by this bug.
In this PR i just added it to fields, but it can also be done in the other way.
> Unmasked 'application_id' field in DRF GCMDeviceSerializer

- push_notifications/utils.py
It only contains `get_expired_tokens`, which is not importable anymore,
since apns_fetch_inactive_ids has been removed in 3998996.
Ref: https://github.com/jleclanche/django-push-notifications/issues/389
> Remove push_notifications.utils

- push_notifications/api/rest_framework.py
The method 'user.is_authenticated()' is deprecated,
and it is removed in the v2 release of django.
> Fix authentication check for django 2.0

- push_notifications/gcm.py
- tests/test_models.py
`gcm._cm_send_request` mutates its `data` argument by calling `dict.pop` for all items in `FCM_NOTIFICATIONS_PAYLOAD_KEYS` and then using the rest as `payload["data"]`. However, since this function may be called more than once from `push_notifications.GCMDeviceQuerySet.send_message`, with same dict as `data` argument, only the first call will have extra values in `payload["notification"]`.
Suggested fix creates a copy of the argument before mutating it. A test case that reproduces the error if ran without the fix is also included.
> Fix gcm mutating extra args

- push_notifications/apns.py
APN bulk message fail when sent with localized keys and badge function. It results in a TypeError as the lambda function is not JSON serializable.
> Fix APN bulk messages

- push_notifications/gcm.py
Added "android_channel_id" notification parameter as per doc (https://firebase.google.com/docs/cloud-messaging/http-server-ref) in order to enable custom notification sound on Android Oreo devices.
>  Added FCM channels support for custom notification sound on Android Oreo 

- .travis.yml
- README.rst
- push_notifications/conf/__init__.py
- push_notifications/conf/legacy.py
- push_notifications/models.py
- tox.ini
- Pin flake8 (can be updated later)
- Stop running tests on 3.4 & 3.6, and use 3.7 instead (xenial in travis isn't a fan of multiple pytrhon versions with tox)
- Run against Django 2.2 instead of master. Master is `3.0.0-alpha.0`, and not stable for our use
> Fix problems with CI

- setup.cfg
Hi
Without this it is impossible to install using pip when running python 3.7.
> Add support for python 3.7

- push_notifications/webpush.py
- tests/settings.py
- tests/test_legacy_config.py
Hi,
there was a hidden problem occur frequently when sending notification to WebPushDevice specially with Google Chrome! when you have several devices say some firefox and some chrome, if first notification sent to chrome device, there will no bug, but if the first notification sent to firefox device sending to any of chrome devices will fail. I have search the web but no clear solution for it found out there, that lead me to guess it is a library bug. I found that you pass settings.PUSH_NOTIFICATIONS_SETTINGS['WP_CLAIMS'] via `LegacyConfig` to `pywebpush.webpush`. the `webpush` method alter given vapid_claims and inject `aud`, `exp` into it **once**.
It is a bad practice to change such settings in this way at runtime. It also lead to a hidden bug that if first device is firefox, its …
> Solve `Push failed: 403 Forbidden` problem with Chrome

- CHANGELOG.md
- setup.cfg
We should probably write a bit more in the changelog before merging! Feel free to create a PR to this branch, `release-v1.7.0`, or push your commits if you are a part of jazzband, or just comment.. :smile: 
Commits since last release:
```
* 455a027 (HEAD -> release-v1.7.0, upstream/release-v1.7.0, v1.7.0) Release 1.7.0
* 2ce2837 (upstream/master) Add support for python 3.7 (#492)
* a73253a Fix problems with CI (#501)
* c4a0d71 README: Update APNs link
* 9182958 flake8: Ignore E503 (use Black style)
* 4962944  Add FCM channels support for custom notification sound on Android Oreo
* 45f0e96 Fix APN bulk messages
* 6f7b80d Avoid mutating arguments in `gcm._cm_send_request`
* e335ac6 Fix error when send a message and the device is not active
* 600495b gcm: Simplify some code
* 8c73a77 Fix …
```
> Release 2.0.0

- push_notifications/apns.py
- tests/test_apns_push_payload.py
- tox.ini
This Pull Requests adds to the existing apns-collapse-id PR by adding the requested basic test to ensure the collapse_id is being set and passed to apns2.
> apns-collapse-id

- push_notifications/apns.py
- setup.cfg
- tox.ini
* Reorders the Payload arguments to support latest pyapns2 0.6.0.
* Selects correct version of pyapns2 based on current python version.
* Update tox.ini to test both versions of pyapns2.
Resolves: #515, #518, #520
> Support newest version of pyapns2 with backwards compatibility

- tests/test_models.py
- tests/test_wns.py
The last remaining warning is:
`Remove the context parameter from HexIntegerField.from_db_value(). Support for it will be removed in Django 3.0`.
We'll need a solution for either replacing HexIntegerField or ditching older Django versions.
> Squash some warnings

- push_notifications/fields.py
Django 3.0 will remove `context` from the signature for the `from_db_value` method. This is showing a warning when I run the tests locally. 
```
RemovedInDjango30Warning: Remove the context parameter from HexIntegerField.from_db_value(). Support for it will be removed in Django 3.0.
```
These extra parameters are not used, so we could make them part of an asterisk parameter to avoid the warning, and keep the compatibility.
> Make unused arguments part of an asterisk parameter

- README.rst
- push_notifications/migrations/0007_uniquesetting.py
- push_notifications/models.py
- push_notifications/settings.py
- tests/settings_unique.py
- tests/tst_unique.py
- tox.ini
I saw the PR https://github.com/jazzband/django-push-notifications/pull/487 and the https://github.com/jazzband/django-push-notifications/pull/487#issuecomment-499132978 by @odinuge and decided to implement just the registration_id unique changes.
Thanks to @goinnn for the work :)
The PR will close the following Issues: #442, #184, #41
I tried to implement testing as smooth as possible but for testing the unique registration_id i have to recreate the database. If anyone has a better idea it's more than welcome :blush:.
> Added setting to make registration_id fields on all device models unique

- .gitignore
- .travis.yml
- README.rst
- setup.cfg
- tests/tst_unique.py
- tox.ini
We're trying to upgrade to Django 3.0 as soon as possible, so I'm going through all our dependencies and helping ensure they work on the latest version of everything.
> Test python 3.8 and Django 3.0 and align doc version specs

- push_notifications/gcm.py
There is a small typo in push_notifications/gcm.py.
Should read `optionally` rather than `optionnally`.
> docs: Fix simple typo, optionnally -> optionally

- push_notifications/api/rest_framework.py
`lookup_field` was declared in `DeviceViewSetMixin` and never used. Instead the create method referred to string literal instead of this field. 
Now the field is used and `registration_id` is no loger hardcoded in create method. 
You can now inherit from `DeviceViewSetMixin`, redefined the `lookup_field` and use if with your views instead of having to rewrite the `create` method yourself
> registration_id no longer hard-coded in DeviceViewSetMixin

- README.rst
Updated README: added info about APNS_AUTH_KEY_PATH, APNS_AUTH_KEY_ID, APNS_TEAM_ID settings for using Apple's p8 push certificates.
This addresses issues #455  and #527
> Updated README: added info about APNS_AUTH_KEY_PATH, APNS_AUTH_KEY_ID, APNS_TEAM_ID

- README.rst
I had some problems with APNS settings and I've lost some hours to figure out what's wrong:
1. I've tried to use debug certificate from Apple, without knowing that I had an app built with release flag.
2. It took me a long time to realize that ``APNS_USE_SANDBOX`` takes ``DEBUG`` value as default.
Because of these two points I got ``BadDeviceToken`` for some hours :(
> Add some details to APNS settings description

- push_notifications/admin.py
- push_notifications/models.py
swapping from ugettext_lazy to gettext_lazy. If I find any other Django 4.0 warnings I will update/make a new PR.
> Django 4.0 warnings

- push_notifications/models.py
I found this problem during auditing your codebase. [Read the full report](https://django.doctor/jazzband/django-push-notifications/)
> Improve efficiency of ORM lookups

- push_notifications/api/rest_framework.py
- push_notifications/compat.py
- push_notifications/conf/base.py
- push_notifications/conf/legacy.py
- setup.cfg
- tox.ini
Since Python 2.x is EOL and also Django before 2.2 tests and code are updated to work with python3.
> Drop python 2.x and django before 2.2

- README.rst
- push_notifications/admin.py
- push_notifications/apns.py
- push_notifications/exceptions.py
- push_notifications/gcm.py
- push_notifications/webpush.py
- setup.cfg
- tests/_mock.py
- tests/test_apns_models.py
- tests/test_apns_push_payload.py
- tests/test_gcm_push_payload.py
- tests/test_legacy_config.py
- tests/test_models.py
- tests/test_wns.py
- tox.ini
In some use-cases this package is used only to serve a subset of available push services.
In this case having every push-library as a required dependecy may cause problems with the environment (ie: dependecies of dependency).
This PR turns APNS and webpush as optional dependencies using [`extras_require`](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies) option.
> Make push optional dependecies

- push_notifications/fields.py
As of now `HexIntegerField` relies on `connection.settings_dict["ENGINE"]` to determinate if the database supports specific feature.
Since a custom engine may be defined by any user this has some limitation because engines are hard-coded.
The preferred approach would be to use `connection.feature_class.<feature>`, but ATM there is no flag in these classes which may help here (ie: `supports_unsigned_integers`).
My solution here is to rely on `connection.vendor` because it should be more robust and could handle subclassing of any existent backend, if that backend has some kind of differences it could just override `vendor` attribute (ie: `postgresql` -> `custom-postgresql`).
Also this saves us some configurations since `django.db.backends.postgresql`, …
> Change feature detection logic for database field

- .github/workflows/test.yml
- tox.ini
Django 3.0 and 3.1 already got on EOF
I also had forgot to add the Django 4.0 on GHA
> chore: test only active Django versions

- .github/workflows/test.yml
- tests/settings.py
- tests/settings_unique.py
- tox.ini
Looking at the [docs](https://github.com/ymyzk/tox-gh-actions#advanced-examples) of tox-gh-action
we could not have the test logic on both places, reducing the duplication and complexity of testing
the new DRF 3.13.0 is full compatible with django 4.0 and it does not need anymore the pytz package
> chore: dry tests, use newer DRF on tests

- tox.ini
The django master branch has an incompatibility with the latest django rest framework.
> Add django 4.1, remove master branch

- README.rst
`send_message` for GCM/FCM topics now requires `cloud_type` argument to be provided, but it is not shown in the docs, therefore copying the snippet will not work straight away.
I had to lookup function definition, hope this will save some time for other people :)
> Update topic send_message docs in README

- push_notifications/api/rest_framework.py
- tests/test_rest_framework.py
Hopefully solves https://github.com/jazzband/django-push-notifications/issues/537
> Allow APNS tokens of variable length.

- README.rst
- docs/FCM.rst
- push_notifications/admin.py
- push_notifications/conf/__init__.py
- push_notifications/conf/app.py
- push_notifications/conf/base.py
- push_notifications/conf/legacy.py
- push_notifications/gcm.py
- push_notifications/models.py
- push_notifications/settings.py
- setup.cfg
- setup.py
- tests/responses.py
- tests/test_admin.py
- tests/test_app_config.py
- tests/test_dict_to_message.py
- tests/test_gcm_push_payload.py
- tests/test_legacy_config.py
- tests/test_models.py
- tox.ini
Use new FCM v1 API by using firebase_admin SDK.
- Removed GCM type
- Added firebase-admin
- Updated documentation
- Updated tests
Resolves #546
> Add FCM v1 API

- docs/FCM.rst
- push_notifications/models.py
documentation fix https://github.com/jazzband/django-push-notifications/issues/703
mandatory dependency fix https://github.com/jazzband/django-push-notifications/pull/702#discussion_r1489160018
> make firebase-admin an optional dependency

- push_notifications/models.py
As pointed out in this comment https://github.com/jazzband/django-push-notifications/pull/702#discussion_r1489160018 importing `firebase_admin` or `gcm` at top level in `models.py` turns the `firebase_admin` package as a mandatory requirements while it should not.
To address this I have moved the imports inside the appropriated methods. This allow the codebase to run even without the firebase package (which is optional).
> Fix imports of FCM to keep it as an optional dependency

- README.rst
- push_notifications/gcm.py
- setup.cfg
- tests/test_admin.py
- tests/test_gcm_push_payload.py
- tests/test_models.py
- tox.ini
Closes #712. Let me know if I need to do anything else.
> Changed firebase-admin's deprecated send_all method for send_each

- README.rst
> Fix spelling in README

- .github/workflows/release.yml
recent releases have been missing wheels eg https://pypi.org/project/django-push-notifications/3.1.0/#files
not sure why: what you are doing in the release workflow is deprecated but so far as I know should work
anyway here is a non-deprecated version
> modernize distribution builds

- push_notifications/apns.py
- tests/test_apns_models.py
If we have a duplicated registration ID on the APNSDevice model and we get an unregistered error after sending a message, it raises a `MultipleObjectsReturned` exception (get() returned more than one APNSDevice -- it returned ...!).
In order to fix this, we can update all the records with that registration ID instead of using `objects.get`.
> Fix error handling on duplicated APNS devices

- push_notifications/migrations/0011_alter_apnsdevice_registration_id.py
- push_notifications/models.py
When having huge list apns devices without the unique setting activated (UNIQUE_REG_ID) updating devices via the drf-endpoint becomes very slow. Adding an index resolves that.
For reference our current prod-environment have select-statements to this fields taking up to 9 seconds under heavy load.
> Add db_index=True for registration_id on APNSDevice model

- push_notifications/apns_async.py
- push_notifications/exceptions.py
- tests/test_apns_async_models.py
- tests/test_apns_async_push_payload.py
Previous version implemented aioapns in a way that made it hang indefinetly. Especially when receiver list contaned a lot of bad tokens.
Having a lot of bad tokens still affects the reliability and transfer speed of notification sets, which is why this fix also deactivate devices for error codes BadDeviceToken and DeviceTokenNotForTopic unlike previous versions.
Tagging @pomali who initially did the aoiapns integration in case you have any feedback.
> Fix #744: Bulk messages with aoiapns not working properly

- .github/dependabot.yml
This PR is to address the re-occuring issue of managing dependencies or
transitive dependency for the project - including but not limited to,
security updates.
With dependabot, we are one step closer with keeping underlying
dependencies up-to-date, minimizing the overhead of manual intervention.
This would require constant review of the bot PRs, to ensure updates or security updates
are in-line with future release and backward compatible with this
package/libarary.
> feat(dependabot): automate dependency management and security updates

- push_notifications/apns_async.py
- tests/test_apns_async_push_payload.py
Re-do of #745 
Changes in the #745 was https://github.com/jazzband/django-push-notifications/commit/314a48410362f18f766608753a93248f7fc0eba6
This PR introduces support for the mutable_content property in the aioapns library, which was previously available only in apns2. The mutable_content property allows notifications to be modified by a Notification Service Extension before being delivered to the user.
This is related to https://github.com/jazzband/django-push-notifications/issues/320 and https://github.com/jazzband/django-push-notifications/pull/350.
Earlier support was available in the apns.py file, now added to apns_async.py.
> Add Support for mutable_content in aioapns

- push_notifications/apns_async.py
- tests/test_apns_async_push_payload.py
- add `content_available` argument for async version of apns. Argument is sent as `content-available` to apns
- add tests for `content_available`
- format `apns_async.py`
(similar to #760)
> Add support for `content_available` for apns async

- push_notifications/apns_async.py
APNS expect mutable-content as int in the message payload.
Setting `mutable_content` to True, will set `mutable-content` to 1.
> Make mutable-content int (1) instead of bool (True)

- .github/workflows/test.yml
- setup.cfg
- tox.ini
This change here documents the support for Python 3.11+, while fixing the broken pipeline due to the deprecated support for `Ubuntu 20.04` runners.
> Add support for py312 py313

- setup.cfg
This PR pins the `aioapns` dependency to versions `>=3.1,<4.0` in `setup.cfg` to avoid breaking changes introduced in `aioapns` 4.0.
The `APNsKeyConnectionPool` in `aioapns` 4.x expects a `key` string instead of a `key_path`, which would currently break existing integrations.
For now, pinning ensures stability and compatibility. A follow-up PR will handle the upgrade to support the newer API when ready.
Fixes: #766
> Pin `aioapns` Dependency to `<4.0` to Prevent Breaking Changes

- push_notifications/apps.py
Django projects might set `DEFAULT_AUTO_FIELD` to different values than `AutoField`.
In fact modern Django versions generate a settings.py file that uses `BigAutoField` by default.
The result is that when using this library in such a project, `makemigrations` will always attempt to create migrations for push_notification's models.
By adding an explicit `AppConfig`, Django knows that this application uses `AutoField`, regardless of the `DEFAULT_AUTO_FIELD` setting.
See:
- https://docs.djangoproject.com/en/5.2/ref/applications/#django.apps.AppConfig.default_auto_field
- https://docs.djangoproject.com/en/5.2/ref/applications/#configuring-applications
Fixes https://github.com/jazzband/django-push-notifications/issues/662
> Add explicit Django AppConfig to set default_auto_field

- push_notifications/api/rest_framework.py
When registering a Web Push endpoint in the backend, it is essential to save the complete endpoint URL provided by the browser instead of just the token or identifier. This is because the full URL includes not only the device identifier but also the specific push service host, path and query parameters necessary for proper authentication and message delivery. These can change over time, storing only the token or a partial value risks losing the ability to send reliable and secure notifications, thus affecting the overall stability of the push notification system.
Therefore, the lookup_value_regex should allow for almost any character, as the value is sent from the frontend using encodeURIComponent, and URLs tend to be very complex and diverse.
> Fix webpush API

- push_notifications/api/rest_framework.py
- push_notifications/apns.py
- push_notifications/apns_async.py
- push_notifications/conf/__init__.py
- push_notifications/conf/app.py
- push_notifications/conf/base.py
- push_notifications/conf/legacy.py
- push_notifications/exceptions.py
- push_notifications/fields.py
- push_notifications/gcm.py
- push_notifications/models.py
- push_notifications/webpush.py
- push_notifications/wns.py
* Add type anotation to methods and functions
* Use full path for imports instead of `..`
* Remove legacy Union, Optional, Dict and List in functions and methods
* Use isinstance for type check instead of using the type itself
* Replace type anotation which was using `any` with the right `Any`
> Add type anotation to methods and functions

- push_notifications/admin.py
- push_notifications/api/rest_framework.py
- push_notifications/apns.py
- push_notifications/apns_async.py
- push_notifications/conf/__init__.py
- push_notifications/conf/app.py
- push_notifications/conf/base.py
- push_notifications/conf/legacy.py
- push_notifications/exceptions.py
- push_notifications/fields.py
- push_notifications/gcm.py
- push_notifications/models.py
- push_notifications/webpush.py
- push_notifications/wns.py
This branch improves type safety and consistency across the codebase.
* Added and refined type annotations for configs, managers, and helper functions.
* Replaced loose type checks with more explicit `isinstance` checks.
* Updated import paths for clarity and correctness.
* Refactored `_chunks` usage to use the correct variables.
* Removed redundant `return` in validator functions that never return.
* Unified `ManagerType` as a union of the supported config classes.
* Used `Union`, `Optional`, `List`, and `Tuple` from `typing` for **backwards compatibility** (pre-3.10 support).
> Update type anotations
