README.rst, push_notifications/api/__init__.py, push_notifications/api/rest_framework.py, push_notifications/api/tastypie.py, push_notifications/fields.py, setup.py, tests/__init__.py, tests/test_rest_framework.py
Almost 100% based on PR #102. One minor update to the DeviceMixin for DRF v3 support. Also restricts device access to only those uploaded by the user.
=> Django Rest Framework Support

push_notifications/api/rest_framework.py, tests/mock_responses.py, tests/test_rest_framework.py
Added tests for new serializer validators
Fixed tab/spaces formatting
=> Fixes issue #207 Added validaiton for gcm device_id max values

push_notifications/api/tastypie.py
=> use absolute import to avoid referencing current file

push_notifications/fields.py
=> Add preferred name of Postgres backend introduced in Django 1.9

push_notifications/apns.py
Add support of title key in push notification alert property
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW4
=> Add APN alert title support

push_notifications/api/rest_framework.py
If the request method is PATCH attrs is not guaranteed to contain
either "id" or "registration_id"
=> Fix UniqueRegistrationSerializerMixin validate method.

push_notifications/apns.py
Support for mutable-content flag, new in iOS 10. #313
=> Support for mutable-content flag in APNS

push_notifications/conf/legacy.py
=> Fix incorrect setting key lookup value

push_notifications/apns.py
Updated the link to APNS overview.
=> Removind dead link to iOS Library

push_notifications/conf/legacy.py, tests/test_legacy_config.py
=> Add empty class to avoid None triggering ImproperlyConfigured

push_notifications/admin.py
check for them in django admin to correctly display error message.
=> Because NotRegistered and InvalidRegistration do not throw GCMError

push_notifications/admin.py, push_notifications/gcm.py, push_notifications/models.py, tests/responses.py
Fixes display issue when sending test bulk message > max_recipients
Adds original_registration_id to results dict on GCMError
Addresses:
https://github.com/jleclanche/django-push-notifications/issues/354
&
https://github.com/jleclanche/django-push-notifications/issues/391
=> Fixes error when sending django admin test gcm message.

README.rst
=> Fix parameter name cloud_message_type on README

push_notifications/migrations/0006_webpushdevice.py
added `on_delete` parameter in last migration (0006) to make it compatible with Django 2.0
=> hotfix for Django 2.0

push_notifications/migrations/0006_webpushdevice.py
=> add on_delete cascade on WebPushDevice.user

README.rst, docs/APNS.rst
Incorporate https://github.com/jazzband/django-push-notifications/pull/425 into a separate file instead of readme
=> Add docs folder

push_notifications/apns.py, push_notifications/conf/app.py, push_notifications/conf/base.py, push_notifications/conf/legacy.py, push_notifications/models.py, tests/test_app_config.py
This is simply a rebase of an older pull request https://github.com/jazzband/django-push-notifications/pull/426. Resolves https://github.com/jazzband/django-push-notifications/issues/351.
=> APNs Auth Key Support

push_notifications/admin.py
the return format has changed for some reason, I adapted the bulk send action from admin site to not crash on send.
Fixes issue #568
=> #567 Fixes crash on bulk_send test message operation from admin

README.rst
The main branch doesn't exist, may I fix it?
=> Show coverage badge in README.

push_notifications/fields.py, tests/test_fields.py
=> Fix: HexadecimalField accepts non-hex values

push_notifications/apns_async.py, tests/test_apns_async_push_payload.py
=> Add Support for category in aioapns
